version: '2'
services:
  zipkin-cassandra:
    image: openzipkin/zipkin-cassandra
    container_name: zipkin-cassandra
    networks:
      - internal
    restart: always
    volumes:
      - cassandra:/var/lib/cassandra
    environment:
      - "constraint:type==infra"

  zipkin-cron:
    image: openzipkin/zipkin-dependencies
    container_name: zipkin-cron
    networks:
      - internal
    restart: always
    entrypoint: crond -f
    depends_on:
      - zipkin-cassandra
    environment:
      - STORAGE_TYPE=cassandra
      - CASSANDRA_CONTACT_POINTS=zipkin-cassandra
      - "constraint:type==infra"
      - "affinity:container==zipkin-cassandra"

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    networks:
      - internal
      - proxy
    restart: always
    depends_on:
      - zipkin-cassandra
    environment:
      - STORAGE_TYPE=cassandra
      - CASSANDRA_CONTACT_POINTS=zipkin-cassandra
      - SELF_TRACING_ENABLED=false
      - VIRTUAL_HOST=${ZIPKIN_VIRTUAL_HOST}
      - VIRTUAL_PORT=9411
      - LETSENCRYPT_HOST=${ZIPKIN_VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - "constraint:type==infra"
      - "affinity:container==zipkin-cassandra"

volumes:
  cassandra:

networks:
  internal:
  proxy:
    external:
      name: proxy_back
